### PR TITLE
Km login button bug

### LINKED ISSUE #15: Iteration 2: User Login Testing
- [ ] test user login

- [ ] test user logout

- [ ] sad path testing where appropriate

### LINKED ISSUE #31: Bug: Need to hide/remove original login button
Need to hide/remove original login button when login form component displays & button also persists through routing back to main page

### PR DESCRIPTION
**Pull request by Kristiannmiller**
## Description
This PR:
- Addresses the bug in the original login button that kept the button displayed on the login page
- Properly toggles the login/logout button on the homepage
- Rearranges the test in the login-test-js file asserting that the user is greeting on login
- Removes vestigial  comments, console.logs, and variables throughout the codebase
- closes #31 
- closes #15 

## Motivation and Context
This PR was needed in order to address a few bugs that were keeping us from moving on to iteration 4.

## How Has This Been Tested?
Tested using Jest, in the terminal, and visually in the browser via npm start

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code follows the code style of this project.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: src/App/App.js [hunk 1]
```diff
@@ -14,48 +14,35 @@ class App extends Component {
...
   }
   loginButtonFunction = () => {
-    const path = window.location.pathname
-    console.log(path)
-    if(!this.state.user.id && path === '/login') {
-      return false
-    } else {
-      return true
-    }
+    this.setState({isOnHomePage: false})
```
Comment (aemcdonald) [inline src/App/App.js:36]: Great job adding a toggle feature here to trigger a re-render of the page

File: src/Login/Login.test.js [hunk 2]
```diff
@@ -29,31 +28,24 @@ describe('Login', () => {
     expect(screen.getByText('Please type your email and password to sign in')).toBeInTheDocument()
   })
 
-  it('should welcome the user after submitting login info', async() => {
+  it('should welcome the user after submitting login info', async () => {
```
Comment (aemcdonald) [inline src/Login/Login.test.js:31]: Great fix here, looks like we were on the right track but need to make sure that we are mocking all functions before we render any components.

**Review by aemcdonald — APPROVED** [review]
Great job fixing the Login test, seems like we need to make sure we precede any renders with our mocks moving forward. Awesome job fixing that login button bug!
